FROM node:20-slim AS builder
WORKDIR /app
COPY client/package.json client/package-lock.json ./
RUN npm ci
COPY client/ ./
# Vite usará .env.production automáticamente durante el build
RUN npm run build

FROM nginx:stable-alpine
ARG NGINX_PROXY_PASS
COPY client/nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=builder /app/dist /usr/share/nginx/html
EXPOSE 80