services:
  - type: web
    name: backend-api
    env: docker
    dockerfilePath: ./backend_api/Dockerfile
    envVars:
      - key: PORT
        value: 8000

  - type: web
    name: frontend
    env: docker
    dockerfilePath: ./client/Dockerfile
    healthCheckPath: /
    routes:
      - type: rewrite
        source: /*
        destination: /